export default {
  THE_DUDE: "THE_DUDE",
  INICIO_RECEIVED: "INICIO_RECEIVED",
  EQUIPO_RECEIVED: "EQUIPO_RECEIVED",
  INSTALACIONES_RECEIVED: "INSTALACIONES_RECEIVED",
  TARIFAS_RECEIVED: "TARIFAS_RECEIVED",
  SERVICIOS_RECEIVED: "SERVICIOS_RECEIVED",
  TECNICAS_RECEIVED: "TECNICAS_RECEIVED",
  CONTACTO_RECEIVED: "CONTACTO_RECEIVED",
  INITIALIZE_FIREBASE: "INITIALIZE_FIREBASE",
  UPLOAD_PIC: "UPLOAD_PIC"
};
