export default {
  CONTENIDOS_RECEIVED: "CONTENIDOS_RECEIVED",
  MOVE_CAROUSELL: "MOVE_CAROUSELL",
  TOGGLE_MOBILE_TOP_MENU: "TOGGLE_MOBILE_TOP_MENU",
  IS_THE_DUDE: "IS_THE_DUDE",
  CIERRA_COOKIES_AVISO: "CIERRA_COOKIES_AVISO"
};
