export default {
  THE_DUDE: "THE_DUDE",
  INICIO_RECEIVED: "INICIO_RECEIVED",
  INSTALACIONES_RECEIVED: "INSTALACIONES_RECEIVED",
  TARIFAS_RECEIVED: "TARIFAS_RECEIVED",
  SERVICIOS_RECEIVED: "SERVICIOS_RECEIVED",
  CONTACTO_RECEIVED: "CONTACTO_RECEIVED"
};
